import Link from 'next/link';

const DISCO_CATALOG_URL = 'https://sonant.disco.ac/cat/152887908';

const faqs = [
  {
    q: 'What is Sonant?',
    a: 'Sonant is a creative platform built for composers who write custom music. It combines a brief catalog, a brief generator, and a live review program — all built around the idea of practicing the way professional composers actually work: by writing to a brief.',
  },
  {
    q: 'What\'s the difference between a Sonant brief and a community brief?',
    a: 'Sonant briefs are curated by the Sonant team and written to real industry specs — the kind of direction a music supervisor sends a composer for a brand, film, or game project. Tracks submitted to Sonant briefs go through a review process and, if accepted, get added to the Sonant catalog and pitched to buyers. Community briefs are generated by individual composers using the Brief Generator. Anyone can write to any community brief and upload their track directly — no review process, just practice and sharing.',
  },
  {
    q: 'How do I submit music to a Sonant brief?',
    a: 'Open any Sonant brief from the catalog, read it carefully, write your track, and click "Submit a Track" on the brief page. There\'s no fee and no form to fill out — just submit the track. You\'ll get a written response regardless of outcome.',
  },
  {
    q: 'What happens after I submit?',
    a: 'Every submission gets reviewed and receives a written response. If your track is accepted, it gets added to the Sonant catalog and actively pitched to brands, agencies, studios, and music supervisors. If it\'s not accepted, you\'ll get specific notes on why and what would have made the difference. You keep full ownership of your music no matter what.',
  },
  {
    q: 'What are the terms if my track gets placed?',
    a: 'You own your music — Sonant is non-exclusive. If Sonant brokers a placement, you keep 70% of the sync fee. Sonant earns only when you do. You\'re free to pitch the same track to other libraries or use it anywhere else.',
  },
  {
    q: 'What is the Brief Generator?',
    a: 'The generator builds a full creative brief based on the type of project (brand, film, or game), the category, mood, and genre you select. It produces the same kind of direction a music supervisor would send — scene context, emotional arc, instrumentation notes, reference points, and a deadline. Use it to practice writing to spec, then upload your track directly to the brief.',
  },
  {
    q: 'Can I share my community brief with other composers?',
    a: 'Yes. Any logged-in user can view and upload tracks to any community brief. Share the link and let other composers take their own approach to the same brief — it\'s a good way to hear different interpretations of the same creative direction.',
  },
  {
    q: 'What are Music Reviews?',
    a: 'A live music review is a focused 15 or 30-minute session where we listen to your track together, compare it against the brief you wrote to, and give you specific feedback in real time. It\'s faster and more actionable than written notes. Good for checking a track before submission, or understanding why something isn\'t working.',
  },
  {
    q: 'Do I need to create an account?',
    a: 'Yes — an account is required to generate briefs, upload tracks, and submit music. Creating one is free.',
  },
  {
    q: 'Who is Sonant for?',
    a: 'Composers at any level who want to get better at writing custom music and build a catalog worth pitching. Whether you\'re just starting out with sync or have years of experience, the brief catalog gives you real-world practice material and a path to getting your music in front of people who need it.',
  },
];

export default function FAQPage() {
  return (
    <div className="pt-20 pb-24 flex-1">
      <div className="max-w-5xl mx-auto px-6 md:px-10">

        <div
          className="text-[10px] tracking-[0.4em] uppercase text-[#E85D2F] mb-5"
          style={{ fontFamily: "'JetBrains Mono', monospace" }}
        >
          ◆ FAQ
        </div>
        <h1
          className="text-5xl md:text-6xl tracking-tight leading-[1.05] mb-5 max-w-2xl"
          style={{ fontFamily: "'Fraunces', serif", fontWeight: 300 }}
        >
          How Sonant <span className="italic text-[#E85D2F]" style={{ fontWeight: 400 }}>works.</span>
        </h1>
        <p
          className="text-base text-[var(--text-tertiary)] mb-16 max-w-xl leading-relaxed"
          style={{ fontFamily: "'DM Sans', sans-serif" }}
        >
          Everything you need to know about the catalog, the generator, submissions, and music reviews.
        </p>

        <div className="space-y-0 border-t border-[var(--border-base)]">
          {faqs.map(({ q, a }) => (
            <div
              key={q}
              className="border-b border-[var(--border-base)] py-8 grid grid-cols-1 md:grid-cols-[2fr_3fr] gap-6"
            >
              <h2
                className="text-base text-[var(--text-primary)] leading-snug"
                style={{ fontFamily: "'Fraunces', serif", fontWeight: 400 }}
              >
                {q}
              </h2>
              <p
                className="text-sm text-[var(--text-muted)] leading-relaxed"
                style={{ fontFamily: "'DM Sans', sans-serif" }}
              >
                {a}
              </p>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div
          className="mt-16 border border-[var(--border-card)] bg-[var(--bg-card)] p-8 md:p-10 flex flex-col md:flex-row md:items-center justify-between gap-6"
          style={{ borderRadius: '2px' }}
        >
          <div>
            <div
              className="text-[10px] tracking-[0.3em] uppercase text-[#E85D2F] mb-3"
              style={{ fontFamily: "'JetBrains Mono', monospace" }}
            >
              ◆ Ready to start?
            </div>
            <p
              className="text-base text-[var(--text-secondary)] leading-relaxed max-w-md"
              style={{ fontFamily: "'DM Sans', sans-serif" }}
            >
              Browse the catalog, find a brief that fits, and write your music. Or listen to what other composers have already submitted.
            </p>
          </div>
          <div className="flex gap-3 flex-wrap shrink-0">
            <Link
              href="/browse"
              className="px-5 py-3 text-xs tracking-[0.15em] uppercase bg-[#E85D2F] text-[var(--bg-base)] hover:bg-[#FF6E3D] transition-colors whitespace-nowrap"
              style={{ fontFamily: "'JetBrains Mono', monospace", borderRadius: '2px', fontWeight: 500 }}
            >
              ◆ Browse Catalog
            </Link>
            <a
              href={DISCO_CATALOG_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="px-5 py-3 text-xs tracking-[0.15em] uppercase border border-[var(--border-subtle)] text-[var(--text-secondary)] hover:border-[#E85D2F] hover:text-[#E85D2F] transition-colors whitespace-nowrap"
              style={{ fontFamily: "'JetBrains Mono', monospace", borderRadius: '2px' }}
            >
              Listen to the Music
            </a>
          </div>
        </div>

      </div>
    </div>
  );
}
